In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
test=pd.read_csv("/content/drive/MyDrive/Анализ Данных/Kaggle Flight/Data/test_airplanes.csv")
train=pd.read_csv("/content/drive/MyDrive/Анализ Данных/Kaggle Flight/Data/train_airplanes.csv")
train.head()

   Unnamed: 0  index         0         1  ...        27        28        29  target
0           0      0 -0.492317  1.466367  ... -1.134642  0.455824 -0.840537       1
1           1      1 -0.008567  1.139580  ... -0.868660 -1.588205 -0.644534       0
2           2      2  0.262494 -1.708783  ... -0.075973  0.234760  0.082982       1
3           3      3 -1.804729 -0.241023  ...  2.286288 -0.285059  0.638533       1
4           4      4 -0.017279  0.813156  ... -1.574068  1.344927 -2.390142       1

[5 rows x 33 columns]

     Unnamed: 0         0         1  ...        28        29  target
0             0 -0.492317  1.466367  ...  0.455824 -0.840537       1
1             1 -0.008567  1.139580  ... -1.588205 -0.644534       0
2             2  0.262494 -1.708783  ...  0.234760  0.082982       1
3             3 -1.804729 -0.241023  ... -0.285059  0.638533       1
4             4 -0.017279  0.813156  ...  1.344927 -2.390142       1
..          ...       ...       ...  ...       ...       ...     ...
795         795  0.480216 -0.815049  ...  0.725734 -0.649755       0
796         796  0.857515  2.327731  ...  0.206624 -1.724080       1
797         797  0.023109  0.342980  ...  0.443686  0.380687       1
798         798  0.081947 -0.562397  ...  0.799944 -0.439192       1
799         799 -2.227888  0.455428  ... -0.747710  1.665824       1

[800 rows x 32 columns]

In [6]:
from sklearn.linear_model import LogisticRegression # логистическая регрессия
from sklearn.tree import DecisionTreeClassifier # дерево решений
from sklearn.svm import SVC # метод опорных векторов
import xgboost as xgb

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(
                                                train.drop(columns=['index','target','Unnamed: 0']),
                                                train['target'],
                                                test_size=1/3,
                                                random_state=42)

In [8]:
log = LogisticRegression()
tree = DecisionTreeClassifier()
svc = SVC()
xbg = xgb.XGBClassifier()

models = [log, tree, svc, xbg]

for model in models:
    #  fit() - обучение модели/классификатора
    model.fit(X_train, y_train)

    # predict - тестирование
    y_pred = model.predict(X_test)

    # оценка классификатор/модели
    score = accuracy_score(y_test, y_pred)
    print(model)
    print(score)
    print('-'*50)

LogisticRegression()
0.7265917602996255
--------------------------------------------------
DecisionTreeClassifier()
0.8614232209737828
--------------------------------------------------
SVC()
0.8689138576779026
--------------------------------------------------
XGBClassifier()
0.9213483146067416
--------------------------------------------------

In [9]:
model = xgb.XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

score = accuracy_score(y_test, y_pred)
score

0.9213483146067416

In [10]:
test.head()

   Unnamed: 0  index         0  ...        27        28        29
0           0    800  1.432238  ... -0.271966 -1.197476 -0.366255
1           1    801 -0.487362  ...  1.049596 -0.329357 -1.257669
2           2    802  0.962898  ... -1.145836 -0.370616 -0.481098
3           3    803 -1.065925  ...  0.676382  1.070216  0.645921
4           4    804  0.728761  ... -0.472584 -1.116276  0.095643

[5 rows x 32 columns]

In [11]:
y_pred = model.predict(test.drop(columns=['Unnamed: 0', 'index']))
y_pred.shape

(200,)

In [16]:
from google.colab import files
answer = pd.DataFrame(y_pred, columns=['target'])
answer = answer.reset_index()
answer
answer.to_csv('Kaggle_Flight_Zyablitskaya.csv', index=False)
files.download("Kaggle_Flight_Zyablitskaya.csv")