In [67]:
import pandas as pd
import json

def get_X_y(data_json_file):
    X, y = [], []
    with open(data_json_file, 'r', encoding="utf-8") as json_file:
        json_list = list(json_file)
        #print(json_list[0])
        for json_str in json_list:
            item = json.loads(json_str)
            text = item['passage']['text']
            #print(item['passage'].keys())
            questions = item['passage']['questions']
            for q in questions:
                query = q['question']
                ans = q['answers']
                for a in ans:
                    X.append(text+' Query: '+query+' Answer: '+a['text'])
                    y.append(a['label'])
    return X, y

X_train, y_train = get_X_y('C:\\Users\In9.var\Desktop\Projects\data1\\train.jsonl')

train_df = pd.DataFrame({
    'text': X_train,
    'label': y_train
})
train_df

                                                    text  label
0      (1) Но люди не могут существовать без природы,...      1
1      (1) Но люди не могут существовать без природы,...      0
2      (1) Но люди не могут существовать без природы,...      0
3      (1) Но люди не могут существовать без природы,...      1
4      (1) Но люди не могут существовать без природы,...      0
...                                                  ...    ...
11945  (1) Известный американский боец смешанных един...      0
11946  (1) Известный американский боец смешанных един...      1
11947  (1) Известный американский боец смешанных един...      0
11948  (1) Известный американский боец смешанных един...      0
11949  (1) Известный американский боец смешанных един...      1

[11950 rows x 2 columns]

In [68]:
train_df.iloc[100]["text"]

'"(1) Российский вратарь клуба НХЛ "Эдмонтон Ойлерс" Николай Хабибулин принес своей команде победу в матче с действующим обладателем Кубка Стэнли "Чикаго Блэк Хокс". (2) Эта игра состоялась в ночь на 8 ноября в Чикаго и завершилась со счетом 2:1 в пользу "Эдмонтона". (3) Хабибулин отразил 26 из 27 бросков, сообщает официальный сайт НХЛ. (4) Единственную шайбу в ворота "Чикаго" в середине первого периода забросил Фернандо Писани. (5) "Эдмонтон" забил два гола на восьмой минуте третьего периода с интервалом в 14 секунд. (6) Отличились Крис Кертис и Сэм Ганье. (7) После этой победы у "Ойлерс" стало десять очков в 12 матчах, и команда осталась на последнем месте в Западной конференции. (8) Хабибулин в нынешнем сезоне принял участие в 11 матчах. (9) В среднем он отражает 90,5 процента бросков по своим воротам и пропускает по 3,1 шайбы за игру. (10) Один матч россиянин отстоял "на ноль". (11) Из других матчей, сыгранных в ночь на 8 ноября, стоит отметить победу "Вашингтон Кэпиталс" на "Филадельфией Флайерс" (3:2 в овертайме). (12) Нападающий "Вашингтона" Александр Семин забросил шайбу, а его одноклубник Александр Овечкин отдал голевой пас. (13) Один из голов "Филадельфии" на счету Николая Жердева Вратарь "Флайерс" Сергей Бобровский отразил 36 из 39 бросков." Query: Как Николай Хабибулин принес своей команде победу восьмого ноября в Чикаго? Answer: Он поймал все шайбы противника.'

In [69]:
train_df["text"] = train_df["text"].str.replace("(", "")
train_df["text"] = train_df["text"].str.replace(")", "")
train_df["text"] = train_df["text"].str.replace(".", "")
train_df["text"] = train_df["text"].str.replace("«", "")
train_df["text"] = train_df["text"].str.replace("»", "")
train_df["text"] = train_df["text"].str.replace("—", "")
train_df["text"] = train_df["text"].str.replace("  ", " ")
train_df.iloc[100]["text"]

'"1 Российский вратарь клуба НХЛ "Эдмонтон Ойлерс" Николай Хабибулин принес своей команде победу в матче с действующим обладателем Кубка Стэнли "Чикаго Блэк Хокс" 2 Эта игра состоялась в ночь на 8 ноября в Чикаго и завершилась со счетом 2:1 в пользу "Эдмонтона" 3 Хабибулин отразил 26 из 27 бросков, сообщает официальный сайт НХЛ 4 Единственную шайбу в ворота "Чикаго" в середине первого периода забросил Фернандо Писани 5 "Эдмонтон" забил два гола на восьмой минуте третьего периода с интервалом в 14 секунд 6 Отличились Крис Кертис и Сэм Ганье 7 После этой победы у "Ойлерс" стало десять очков в 12 матчах, и команда осталась на последнем месте в Западной конференции 8 Хабибулин в нынешнем сезоне принял участие в 11 матчах 9 В среднем он отражает 90,5 процента бросков по своим воротам и пропускает по 3,1 шайбы за игру 10 Один матч россиянин отстоял "на ноль" 11 Из других матчей, сыгранных в ночь на 8 ноября, стоит отметить победу "Вашингтон Кэпиталс" на "Филадельфией Флайерс" 3:2 в овертайме 12 Нападающий "Вашингтона" Александр Семин забросил шайбу, а его одноклубник Александр Овечкин отдал голевой пас 13 Один из голов "Филадельфии" на счету Николая Жердева Вратарь "Флайерс" Сергей Бобровский отразил 36 из 39 бросков" Query: Как Николай Хабибулин принес своей команде победу восьмого ноября в Чикаго? Answer: Он поймал все шайбы противника'

In [70]:
def get_X_test(data_json_file):
    X1 = []
    X2 = []
    X3 = []
    with open(data_json_file, 'r', encoding="utf-8") as json_file:
        json_list = list(json_file)
        for json_str in json_list:
            item = json.loads(json_str)
            text = item['passage']['text']
            questions = item['passage']['questions']
            for q in questions:
                query = q['question']
                ans = q['answers']
                for a in ans:
                    X1.append(text) #текст
                    X2.append(query) #вопрос
                    X3.append(a['text']) #ответ на вопрос
    return X1, X2, X3

X1, X2, X3 = get_X_test('C:\\Users\In9.var\Desktop\Projects\data1\\val_wtihout.jsonl')

test_df = pd.DataFrame({
    'text': X1,
    'query': X2,
    'answer': X3
})

test_df

,text,query,answer
0,(1) Самый первый «остров» Архипелага возник в ...,Почему Солженицына перевозили спецконвоем?,Так перевозили особо важных заключенных.
1,(1) Самый первый «остров» Архипелага возник в ...,Почему Солженицына перевозили спецконвоем?,"Потому, что был эмигрантом."
2,(1) Самый первый «остров» Архипелага возник в ...,Почему Солженицына перевозили спецконвоем?,"Потому, что он сам вырыл себе землянку."
3,(1) Самый первый «остров» Архипелага возник в ...,Почему Солженицына перевозили спецконвоем?,"Потому, что он побывал на пересылке Красная Пр..."
4,(1) Самый первый «остров» Архипелага возник в ...,Почему Солженицына перевозили спецконвоем?,"Потому, что он был особо важным заключённым и ..."
...,...,...,...
2230,"""(1) Канадский порноактер Лука Рокко Маньотта,...",За что осуждён Рокко Маньотта?,Изнасилование.
2231,"""(1) Канадский порноактер Лука Рокко Маньотта,...",За что осуждён Рокко Маньотта?,Рокко похитил любовника и присвоил его деньги.
2232,"""(1) Канадский порноактер Лука Рокко Маньотта,...",За что осуждён Рокко Маньотта?,Убийство и расчленение тела.
2233,"""(1) Канадский порноактер Лука Рокко Маньотта,...",За что осуждён Рокко Маньотта?,Рокко убил любовника и расчленил его тело.
2234,"""(1) Канадский порноактер Лука Рокко Маньотта,...",За что осуждён Рокко Маньотта?,Кража.

In [71]:
for n in range(20):
    test_df["text"] = test_df["text"].str.replace(f"({n})", "")
test_df["text"] = test_df["text"].str.replace(".", "")
test_df["text"] = test_df["text"].str.replace(",", "")
test_df["text"] = test_df["text"].str.replace("«", "")
test_df["text"] = test_df["text"].str.replace("»", "")
test_df["text"] = test_df["text"].str.replace("—", "")
test_df["text"] = test_df["text"].str.replace("  ", " ")

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_df['text'], train_df['label'], test_size=0.33, random_state=42)

vectorizer = CountVectorizer(ngram_range=(2,5), analyzer='word', max_features = 10000)

X_train_vector = vectorizer.fit_transform(X_train).toarray()
X_test_vector = vectorizer.transform(X_test).toarray()

In [73]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier,LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report

rs = 42

clf = LogisticRegression(random_state=rs)   
clf2 = RandomForestClassifier(random_state=rs, n_jobs =-1)
#clf4 = SVC(random_state=rs)
clf5 = DecisionTreeClassifier(random_state=rs)

clflist = [clf, clf2, clf5]

for clf in clflist:
    print(clf)
    clf.fit(X_train_vector, y_train)
    predictions = clf.predict(X_test_vector)
    print(classification_report(y_test, predictions))
    print('='*50)

LogisticRegression(random_state=42)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

              precision    recall  f1-score   support

           0       0.50      0.63      0.56      2127
           1       0.36      0.24      0.29      1817

    accuracy                           0.45      3944
   macro avg       0.43      0.44      0.42      3944
weighted avg       0.43      0.45      0.43      3944

==================================================
RandomForestClassifier(n_jobs=-1, random_state=42)
              precision    recall  f1-score   support

           0       0.44      0.52      0.48      2127
           1       0.29      0.23      0.26      1817

    accuracy                           0.39      3944
   macro avg       0.37      0.38      0.37      3944
weighted avg       0.38      0.39      0.38      3944

==================================================
DecisionTreeClassifier(random_state=42)
              precision    recall  f1-score   support

           0       0.47      0.62      0.54      2127
           1       0.30      0.20      0.24      1817

    accuracy                           0.42      3944
   macro avg       0.39      0.41      0.39      3944
weighted avg       0.39      0.42      0.40      3944

==================================================

In [74]:
clf = LogisticRegression(random_state=rs)
X_vector = vectorizer.transform(train_df['text']).toarray()
y = train_df['label']
clf.fit(X_vector, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [76]:
for i in range(test_df.shape[0]):
    test_df["text"][i] = test_df["text"][i]+" "+test_df["query"][i]+" "+test_df["answer"][i]
df = vectorizer.transform(test_df["text"]).toarray()
ans = clf.predict(df)
ans = pd.DataFrame(ans, columns=['label'])
ans.reset_index(inplace=True)
ans.to_csv('C:\\Users\In9.var\Desktop\Projects\data1\submition_text_Igor.csv', index=False)