In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
import pandas as pd
test= pd.read_csv("/content/gdrive/MyDrive/ii/test_airplanes.csv")
train= pd.read_csv("/content/gdrive/MyDrive/ii/train_airplanes.csv")
print(train.isna().sum())
print(test.isna().sum())

Unnamed: 0    0
index         0
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            0
26            0
27            0
28            0
29            0
target        0
dtype: int64
Unnamed: 0    0
index         0
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            0
26            0
27            0
28            0
29            0
dtype: int64

In [4]:
train

     Unnamed: 0  index         0  ...        28        29  target
0             0      0 -0.492317  ...  0.455824 -0.840537       1
1             1      1 -0.008567  ... -1.588205 -0.644534       0
2             2      2  0.262494  ...  0.234760  0.082982       1
3             3      3 -1.804729  ... -0.285059  0.638533       1
4             4      4 -0.017279  ...  1.344927 -2.390142       1
..          ...    ...       ...  ...       ...       ...     ...
795         795    795  0.480216  ...  0.725734 -0.649755       0
796         796    796  0.857515  ...  0.206624 -1.724080       1
797         797    797  0.023109  ...  0.443686  0.380687       1
798         798    798  0.081947  ...  0.799944 -0.439192       1
799         799    799 -2.227888  ... -0.747710  1.665824       1

[800 rows x 33 columns]

In [5]:
y = train['target']
X = train.drop('target', axis=1)
X

     Unnamed: 0  index         0  ...        27        28        29
0             0      0 -0.492317  ... -1.134642  0.455824 -0.840537
1             1      1 -0.008567  ... -0.868660 -1.588205 -0.644534
2             2      2  0.262494  ... -0.075973  0.234760  0.082982
3             3      3 -1.804729  ...  2.286288 -0.285059  0.638533
4             4      4 -0.017279  ... -1.574068  1.344927 -2.390142
..          ...    ...       ...  ...       ...       ...       ...
795         795    795  0.480216  ...  0.299899  0.725734 -0.649755
796         796    796  0.857515  ...  0.609614  0.206624 -1.724080
797         797    797  0.023109  ... -0.528109  0.443686  0.380687
798         798    798  0.081947  ...  2.517259  0.799944 -0.439192
799         799    799 -2.227888  ...  0.698506 -0.747710  1.665824

[800 rows x 32 columns]

In [6]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=1/3)

In [8]:
#Логистическая регрессия 
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(model.score(X_test, y_test))

0.700374531835206

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [22]:
# Дерево
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score


tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=1)

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_tree))
print("Recall:", recall_score(y_test,y_pred_tree))
print("Precision:", precision_score(y_test,y_pred_tree))
y_pred_tree = tree.predict(test)

Accuracy: 0.9176029962546817
Recall: 0.96875
Precision: 0.8732394366197183

In [20]:
y = pd.DataFrame(y_pred_tree, columns=['target'])
y.reset_index(inplace=True)
y.to_csv('Sevastyanov.csv', index=False)
files.download("Sevastyanov.csv")

In [21]:
y

     index  target
0        0       0
1        1       0
2        2       1
3        3       1
4        4       1
..     ...     ...
195    195       1
196    196       0
197    197       0
198    198       1
199    199       0

[200 rows x 2 columns]