In [ ]:
# задача 3
N = int(input())

commands = {
    "zero": 0,
    "one" : 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
    "thirteen": 13,
    "fourteen": 14,
    "fifteen": 15,
    "sixteen": 16,
    "seventeen": 17,
    "eighteen": 18,
    "nineteen": 19,
    "twenty": 20,
    "thirty": 30,
    "forty": 40,
    "fifty": 50,
    "sixty": 60,
    "seventy": 70,
    "eighty": 80,
    "ninety": 90
}

reverse_commands = {
    0 : "zero",
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
    8 : "eight",
    9 : "nine",
    10 : "ten",
    11 : "eleven",
    12 : "twelve",
    13 : "thirteen",
    14 : "fourteen",
    15 : "fifteen",
    16 : "sixteen",
    17 : "seventeen",
    18 : "eighteen",
    19 : "nineteen",
    20 : "twenty",
    30 : "thirty",
    40 : "forty",
    50 : "fifty",
    60 : "sixty",
    70 : "seventy",
    80 : "eighty",
    90 : "ninety"
}

for i in range(N):
    line = input()
    list = line.split(' ')
    
    operator = ""
    n1 = n2 = 0
    result = 0

    for i in list:
        if i == "minus" or i == "plus": operator = i
        else:
            if operator == "": n1 += commands[i]
            else: n2 += commands[i]
    
    if operator == "minus": result = n1 - n2
    else: result = n1 + n2
    
    if result < 20 or result%10 == 0: print(reverse_commands[result])
    else: print(reverse_commands[result - result%10], " ", reverse_commands[result%10])

In [2]:
# задача 4
# Для решения задачи участникам предоставляется информация о транзакциях клиентов банка. Объемом около 27000000 миллионов записей. Каждая запись описывает одну банковскую транзакцию. Для каждого из ≈ 20000 тестовых id, участникам необходимо с помощью обученной модели предсказать, в какую из возрастных групп попадает Клиент.

# Подготовлено два набора данных:

# Обучающий transactions_train.csv, в котором для каждой транзакции известна дата, сумма, тип и id клиента;
# Тестовый transactions_test.csv, содержащий те же поля:
# сlient_id – уникальный номер клиента;
# trans_date – дата транзакции (представляет из себя просто номер дня в хронологическом порядке, начиная от заданной даты);
# small_group – группа транзакций, характеризующих тип транзакции (например, продуктовые магазины, одежда, заправки, детские товары и т.п.);
# amount_rur – сумма транзакции (для анонимизации данные суммы были трансформированы без потери структуры).
# На базе данных файлов можно строить различные признаки, которые характеризуют возрастные группы.

# Целевая переменная для обучающего датасета находится в файле train_target.csv.

# В нем содержится информация о Клиенте и метка возрастной группы, к которой он относится:

# client_id – уникальный номер Клиента (соответствует client_id и файла transactions_train.csv);
# bins – метка возраста. В файлe test.csv вам надо предсказать для указанных client_id соответствующую метку группы возраста.
# Участникам также предоставлен информационный файл small_group_description.csv, который содержит расшифровку типов транзакций.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
transactions_train = pd.read_csv('/content/drive/MyDrive/Data Science/11 КЛАСС/transactions_train.csv')
train_target = pd.read_csv('/content/drive/MyDrive/Data Science/11 КЛАСС/train_target.csv')

In [58]:
transactions_test = pd.read_csv('/content/drive/MyDrive/Data Science/11 КЛАСС/transactions_test.csv')
test_target = pd.read_csv('/content/drive/MyDrive/Data Science/11 КЛАСС/test.csv')

In [7]:
transactions_train.head()

   client_id  trans_date  small_group  amount_rur
0      33172           6            4      71.463
1      33172           6           35      45.017
2      33172           8           11      13.887
3      33172           9           11      15.983
4      33172          10           11      21.341

In [8]:
train_target.head()

   client_id  bins
0      24662     2
1       1046     0
2      34089     2
3      34848     1
4      47076     3

In [9]:
transactions_test.head()

   client_id  trans_date  small_group  amount_rur
0      46445           3            0      19.555
1      46445           3            1      27.774
2      46445           4            0      18.114
3      46445           4            1      22.183
4      46445           5            2      45.795

In [59]:
test_target.head()

   client_id
0      28571
1      27046
2      13240
3      19974
4      10505

In [46]:
info_transac_train = transactions_train.groupby('client_id')['amount_rur'].agg(['min', 'max', 'sum', 'mean'])
info_transac_train

             min       max        sum       mean
client_id
4          0.043  1341.802  28404.121  39.450168
6          0.045   315.781  15720.739  21.535259
7          0.043  4505.971  53630.036  69.379089
10         0.045   654.893  34419.365  48.752642
11         0.388  2105.058  26789.404  32.991877
...          ...       ...        ...        ...
49993      0.211  1315.470  24247.544  26.911814
49995      0.690  1243.601  27951.156  28.845362
49996      0.458  1657.546  80900.345  71.089934
49997      0.432   858.240  13293.115  18.591769
49998      0.432   242.807  11861.956  15.168742

[30000 rows x 4 columns]

In [53]:
amount_transactions_train = transactions_train.groupby(['client_id','small_group'])['amount_rur'].count()
counts_train = amount_transactions_train.reset_index().pivot(index='client_id', columns='small_group',values='amount_rur')
counts_train = counts_train.fillna(0)
counts_train.columns = ['small_group_'+str(i) for i in counts_train.columns]
counts_train

           small_group_0  small_group_1  ...  small_group_202  small_group_203
client_id                                ...
4                    0.0          447.0  ...              0.0              0.0
6                    2.0          397.0  ...              0.0              0.0
7                    2.0           79.0  ...              0.0              0.0
10                  12.0          309.0  ...              0.0              0.0
11                   2.0          423.0  ...              0.0              0.0
...                  ...            ...  ...              ...              ...
49993                0.0          206.0  ...              0.0              0.0
49995               14.0          158.0  ...              0.0              0.0
49996                1.0          296.0  ...              0.0              0.0
49997                0.0          372.0  ...              0.0              0.0
49998                0.0          313.0  ...              0.0              0.0

[30000 rows x 202 columns]

In [64]:
train = pd.merge(train_target, info_transac_train,on='client_id')
train = pd.merge(train, counts_train,on='client_id')
train

       client_id  bins  ...  small_group_202  small_group_203
0          24662     2  ...              0.0              0.0
1           1046     0  ...              0.0              0.0
2          34089     2  ...              0.0              0.0
3          34848     1  ...              0.0              0.0
4          47076     3  ...              0.0              0.0
...          ...   ...  ...              ...              ...
29995      14303     1  ...              0.0              0.0
29996      22301     2  ...              0.0              0.0
29997      25731     0  ...              0.0              0.0
29998      16820     3  ...              0.0              0.0
29999       5265     0  ...              0.0              0.0

[30000 rows x 208 columns]

In [ ]:
info_transac_test = transactions_test.groupby('client_id')['amount_rur'].agg(['min', 'max', 'sum', 'mean'])

amount_transactions_test = transactions_test.groupby(['client_id','small_group'])['amount_rur'].count()
counts_test = amount_transactions_test.reset_index().pivot(index='client_id', columns='small_group',values='amount_rur')
counts_test = counts_test.fillna(0)
counts_test.columns = ['small_group_'+str(i) for i in counts_test.columns]

test = pd.merge(test_target, info_transac_test, on='client_id')
test = pd.merge(test, counts_test, on='client_id')
test

In [78]:
train_columns = train.columns
test_columns = test.columns

In [81]:
for i in train_columns:
    x = False
    for j in test_columns:
        if i == j: x = True
    if x == False: print(i)
print("\n________________________________________\n")
for i in test_columns:
    x = False
    for j in train_columns:
        if i == j: x = True
    if x == False: print(i)

bins
small_group_199
small_group_203

________________________________________

small_group_194
small_group_201

In [82]:
train = train.drop(['small_group_199', 'small_group_203'], axis=1)
test = test.drop(['small_group_194', 'small_group_201'], axis=1)

In [85]:
train

       client_id  bins  ...  small_group_200  small_group_202
0          24662     2  ...              0.0              0.0
1           1046     0  ...              0.0              0.0
2          34089     2  ...              0.0              0.0
3          34848     1  ...              0.0              0.0
4          47076     3  ...              0.0              0.0
...          ...   ...  ...              ...              ...
29995      14303     1  ...              0.0              0.0
29996      22301     2  ...              0.0              0.0
29997      25731     0  ...              0.0              0.0
29998      16820     3  ...              0.0              0.0
29999       5265     0  ...              0.0              0.0

[30000 rows x 206 columns]

In [86]:
test

       client_id    min  ...  small_group_200  small_group_202
0          28571  0.078  ...              0.0              0.0
1          27046  0.043  ...              0.0              0.0
2          13240  1.078  ...              0.0              0.0
3          19974  0.432  ...              0.0              0.0
4          10505  0.043  ...              0.0              0.0
...          ...    ...  ...              ...              ...
19995       2565  0.051  ...              0.0              0.0
19996      31255  0.129  ...              0.0              0.0
19997      31539  0.043  ...              0.0              0.0
19998       4288  0.229  ...              0.0              0.0
19999      15323  0.045  ...              0.0              0.0

[20000 rows x 205 columns]

In [91]:
import pandas as pd

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score

In [84]:
X_train = train.drop('bins', axis = 1)
y_train = train['bins']
X_test = test

In [92]:
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
model_predict = xgb.predict(X_test)

In [94]:
model_predict

array([0, 2, 3, ..., 2, 2, 3])